### ISSUE TITLE
Error message when Importing recipes

### ISSUE THREAD

**Issue by wright2me2** [thinkle/gourmet#1014]
### Steps to Reproduce

1. After successfully importing 270 recipes from Mycookbook.com I am receiving the error that I copied into "describe the bug" below.
2.
3.
4.

### Expected Behavior

I keep getting the following error when using Gourmet Recipe:  
Traceback (most recent call last):   
File "C:\Users\Bernie\Documents\GitHub\gourmet\gourmet\threadManager.py", line 97, in run   
File "C:\Users\Bernie\Documents\GitHub\gourmet\gourmet\importers\xml_importer.py", line 70, in do_run   
File "C:\Program Files\Python27\lib\xml\sax\__init__.py", line 33, in parse   
File "C:\Program Files\Python27\lib\xml\sax\expatreader.py", line 107, in parse   
File "C:\Program Files\Python27\lib\xml\sax\xmlreader.py", line 123, in parse   
File "C:\Program Files\Python27\lib\xml\sax\expatreader.py", line 207, in feed   
File "C:\Program Files\Python27\lib\xml\sax\expatreader.py", line 304, in end_element   
File "C:\Program Files (x86)\Gourmet Recipe Manager\plugins\import_export\mycookbook_plugin\mycookbook_importer.py", line 110, in endElement     obj['rating']=int(self.elbuf.strip()) * 2 
ValueError: invalid literal for int() with base 10: 'None' 

### Environment

* Operating System:
* Version or commit id:
* Installed as Flatpak or Python package?:

**Comment by cydanil** [comment]
Thanks for reporting the issue! I was able to reproduce it.

It will be fixed in the next release of Gourmet :)

**Comment by wright2me2** [comment]
How will I know when to get the next release.
    On Friday, November 6, 2020, 02:39:32 PM MST, Cyril Danilevski <notifications@github.com> wrote:  
 
 


Thanks for reporting the issue! I was able to reproduce it.

It will be fixed in the next release of Gourmet :)
