### ISSUE TITLE
Flatpak instal does not run on latest manjaro

### ISSUE THREAD

**Issue by fbobraga** [thinkle/gourmet#1023]
Trying to run after install (based on https://github.com/thinkle/gourmet/blob/master/INSTALL.md):

[fbobraga@pi4 ~]$ /usr/bin/flatpak run --branch=master --arch=x86_64 --command=gourmet io.github.thinkle.Gourmet
bwrap: execvp ldconfig: Exec format error
erro: ldconfig falhou, status de saída 256
[fbobraga@pi4 ~]$

**Comment by fbobraga** [comment]
Understood the problem now: wrong arch (its a raspberry pi, armhf, not a x86_64 computer... will try to run the python form)

**Comment by fbobraga** [comment]
There's support for arm now?

If no, I must reinstall it in python module (I don know what happened: the module seems to not exists anymore... maybe is something related to the distro update)

**Comment by fbobraga** [comment]
figured out what happened: the $HOME/lib/python3.9/site-packages/ changed to $HOME/lib/python3.10/site-packages/ on OS update :P

**Comment by fbobraga** [comment]
now the problem changed:

$ PYTHONPATH='/home/fbobraga/.local/lib/python3.9/site-packages' python -m gourmet
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/fbobraga/.local/lib/python3.9/site-packages/gourmet/__main__.py", line 2, in <module>
    from gourmet.GourmetRecipeManager import launch_app
  File "/home/fbobraga/.local/lib/python3.9/site-packages/gourmet/GourmetRecipeManager.py", line 9, in <module>
    from gourmet import (batchEditor, convert, plugin, plugin_gui, plugin_loader,
  File "/home/fbobraga/.local/lib/python3.9/site-packages/gourmet/batchEditor.py", line 5, in <module>
    from . import gglobals
  File "/home/fbobraga/.local/lib/python3.9/site-packages/gourmet/gglobals.py", line 8, in <module>
    from .image_utils import load_pixbuf_from_resource
  File "/home/fbobraga/.local/lib/python3.9/site-packages/gourmet/image_utils.py", line 13, in <module>
    from PIL import Image, UnidentifiedImageError
  File "/home/fbobraga/.local/lib/python3.9/site-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/home/fbobraga/.local/lib/python3.9/site-packages/PIL/__init__.py)

**Comment by fbobraga** [comment]
so, I download last release and try to reinstall:

$ python setup.py install
  File "/tmp/gourmet-0.17.4/setup.py", line 37
    raise TypeError, \
                   ^
SyntaxError: invalid syntax

**Comment by fbobraga** [comment]
trying to install with 'master':

$ python setup.py install
/tmp/gourmet-master/setup.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import Command
running install
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/lib/python3.10/site-packages/test-easy-install-5316.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/lib/python3.10/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

**Comment by fbobraga** [comment]
installed with sudo and:

$ python -m gourmet
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/__main__.py", line 2, in <module>
    from gourmet.GourmetRecipeManager import launch_app
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/GourmetRecipeManager.py", line 11, in <module>
    from gourmet import (
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/batchEditor.py", line 3, in <module>
    from . import gglobals
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/gglobals.py", line 8, in <module>
    from .optionparser import args
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/optionparser.py", line 2, in <module>
    import argcomplete
ModuleNotFoundError: No module named 'argcomplete'

**Comment by fbobraga** [comment]
installing missing module:

$ python -m pip install argcomplete
Defaulting to user installation because normal site-packages is not writeable
Collecting argcomplete
  Downloading argcomplete-2.0.0-py2.py3-none-any.whl (37 kB)
Installing collected packages: argcomplete
Successfully installed argcomplete-2.0.0

**Comment by fbobraga** [comment]
I must install 'sqlachemy' module too:

$ python -m pip install argcomplete sqlalchemy
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: argcomplete in ./.local/lib/python3.10/site-packages (2.0.0)
Requirement already satisfied: sqlalchemy in ./.local/lib/python3.10/site-packages (1.4.31)
Requirement already satisfied: greenlet!=0.4.17 in ./.local/lib/python3.10/site-packages (from sqlalchemy) (1.1.2)

**Comment by fbobraga** [comment]
trying to run now:

$ python -m gourmet
args = Namespace(db_url='', html_plugin_dir='', threads=False, gourmetdir='', thread_debug_interval=5.0, thread_debug=False, debug_file='', time=False, debug=None)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/__main__.py", line 2, in <module>
    from gourmet.GourmetRecipeManager import launch_app
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/GourmetRecipeManager.py", line 11, in <module>
    from gourmet import (
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/plugin_gui.py", line 8, in <module>
    from .gtk_extras import dialog_extras as de
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/gtk_extras/dialog_extras.py", line 12, in <module>
    from gourmet.image_utils import image_to_pixbuf, make_thumbnail
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/image_utils.py", line 10, in <module>
    from PIL import Image, UnidentifiedImageError
**ModuleNotFoundError: No module named 'PIL'**

...but:

$ python -m pip install PIL
Defaulting to user installation because normal site-packages is not writeable
**ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL**

how solve this now?

**Comment by fbobraga** [comment]
searching on internet, I found some sites tell to use module 'pillow' istead of 'PIL' (I needed to install module 'bs4' too, which 'pillow' depends...): now the error trying to run is this:

$ python -m gourmet
Traceback (most recent call last):
  File "/home/fbobraga/.local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 1222, in __getattr__
    return self._index[key]
KeyError: 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/__main__.py", line 3, in <module>
    launch_app()
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/GourmetRecipeManager.py", line 659, in launch_app
    RecGui.instance()
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/GourmetRecipeManager.py", line 871, in instance
    RecGui.__single = cls()
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/GourmetRecipeManager.py", line 880, in __init__
    GourmetApplication.__init__(self)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/GourmetRecipeManager.py", line 78, in __init__
    self.setup_recipes() # Setup recipe database
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/GourmetRecipeManager.py", line 157, in setup_recipes
    self.rd = recipeManager.default_rec_manager()
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/recipeManager.py", line 85, in default_rec_manager
    return get_recipe_manager(**dbargs)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/recipeManager.py", line 82, in get_recipe_manager
    return RecipeManager.instance_for(**kwargs)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/backends/db.py", line 1873, in instance_for
    cls._instance_by_db_url[url] = cls(file, custom_url)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/backends/db.py", line 1879, in __init__
    self.rd = get_database(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/backends/db.py", line 2156, in get_database
    return RecData.instance_for(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/backends/db.py", line 152, in instance_for
    cls._instance_by_db_url[url] = cls(file, url)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/backends/db.py", line 175, in __init__
    self.update_version_info(gourmet.version.version)
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/backends/db.py", line 507, in update_version_info
    self.do_modify(
  File "/usr/lib/python3.10/site-packages/gourmet-0.17.5-py3.10.egg/gourmet/backends/db.py", line 1434, in do_modify
    qr = table.update(getattr(table.c,id_col)==getattr(row,id_col)).execute(**d)
  File "/home/fbobraga/.local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 1224, in __getattr__
    util.raise_(AttributeError(key), replace_context=err)
  File "/home/fbobraga/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
AttributeError: id


... any ideas what is causing this error?
