### ISSUE TITLE
Web page importer crashes

### ISSUE THREAD

**Issue by ockham** [thinkle/gourmet#320]
Converted from [SourceForge issue 2894996](https://sourceforge.net/support/tracker.php?aid=2894996), submitted by [SourceForge user nobody](https://sourceforge.net/users/?user_id=100) on 2009-11-10 03:32:20 UTC.

Cannot import from Pampered Chef website under 0.15.1 using deb from site on Ubuntu Karmic.  Looks like it should be simple to parse.  If someone doesn't beat me to it, I may try to submit a patch.

Neither of below styles worked (tried multiple recipes):
http://www.pamperedchef.com/our_products/recipesearch/recipedetail.jsp?recipeId=12481
http://www.pamperedchef.com/our_products/recipesearch/printable.jsp?recipeId=12481

Traceback:
CONTENT TYPE =  None
emit ('completed',)
emit ('done',)
Traceback (most recent call last):
  File "/usr/share/gourmet/gourmet/importers/importManager.py", line 83, in finish_web_import
    result = p.test_url(reader.url,reader.data,reader.content_type)
  File "/usr/share/gourmet/gourmet/plugins/import_export/web_import_plugin/generic_web_importer_plugin.py", line 29, in test_url
    if 'html' in content_type:
TypeError: argument of type 'NoneType' is not iterable

**Comment by allenerenee** [comment]
Occasionally, web page importer will claim it is "done" but fail to launch the editor window. Received the following (long) message on most recent incident:

`END DATA
emit ('error', 1, 'Error during importer', 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/gourmet/threadManager.py", line 97, in run\n    self.do_run()\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 210, in do_run\n    parsed = self.parse_webpage()\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 203, in parse_webpage\n    parsed = self.parse()\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 81, in parse\n    self.crawl(tag)\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 105, in crawl\n    self.crawl(child,label)\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 105, in crawl\n    self.crawl(child,label)\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 105, in crawl\n    self.crawl(child,label)\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 105, in crawl\n    self.crawl(child,label)\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 105, in crawl\n    self.crawl(child,label)\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 105, in crawl\n    self.crawl(child,label)\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 105, in crawl\n    self.crawl(child,label)\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 105, in crawl\n    self.crawl(child,label)\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 105, in crawl\n    self.crawl(child,label)\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 109, in crawl\n    self.add_buffer_to_parsed()\n  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export/web_import_plugin/webpage_importer.py", line 156, in add_buffer_to_parsed\n    to_add = to_add.replace(char,unichr(long(tup[1],16)))\nValueError: invalid literal for long() with base 16: \'\'\n')
emit ('done',)
Running recipeMergerPlugin follow up post hook!
WARNING <bound method BrowserPlugin.reset_view of <browse_recipes.BrowserPlugin instance at 0x7f019eaa8b00>> did not return args,kwargs
do_importer returns importer: <MenuAndAdStrippingWebParser(importer, initial)>
`

**Comment by googlymog** [comment]
I have worked with this part of Gourmet recently and would be happy to help troubleshoot this issue.  Could you provide the url that caused this error so I can reproduce it?

**Comment by allenerenee** [comment]
The most recent instance happened at this address: 
http://theurbanposer.com/perfect-dairy-free-almond-flour/
