### ISSUE TITLE
Repository versus release versions

### ISSUE THREAD

**Issue by mMerlin** [thinkle/gourmet#798]
What is the state/status/version of the master branch of the repository compared to the release versions?

Looking at 'releases', it looks like 0.17.4 should be the latest version, but when I git clone the repository, and build from that,
$ gourmet --version
shows
0.17.0
Is the repository actually older, or is it that the version information has not been updated, so the 0.17.0 that I see is out of date?

**Comment by ockham** [comment]
I think you're seeing the Gourmet version from the package you installed (as you mention in your other bug report, #796). Try `cd`ing into the directory to which you cloned gourmet, and run `bin/gourmet --version` from there.

**Comment by mMerlin** [comment]
The original ubuntu apt-get install went to /usr/bin while sudo python setup.py install went to /usr/local/bin.  And yes, the search path was getting the wrong one.

I exported the minimal initial recipes, did apt-get purge to fully get rid of the initial install.  Now I will have only a single version around.  At least till I am more comfortable with the environment.

BTW,
```
sudo python setup.py install
```
updates po/gourmet.pot, so the 'standard' install followed by
```
git status
```
shows the project as modified.  For myself, I could run without the install, but the rest of the family is not as comfortable with running from the source folder.  Besides, I am going to be exploring that code, and others are not going to want my test versions.

That installed version is not directly runnable.  From the home (not repository) directory,
```
$ gourmet
Traceback (most recent call last):
  File "/usr/local/bin/gourmet", line 16, in <module>
    from gourmet import GourmetRecipeManager
  File "/usr/local/lib/python2.7/dist-packages/gourmet/__init__.py", line 5, in <module>
    import gglobals
  File "/usr/local/lib/python2.7/dist-packages/gourmet/gglobals.py", line 5, in <module>
    from util import windows
ImportError: No module named util
```
Specifying the full path to .../gourmet/bin/gourmet does not work either.  Have to cd to the gourmet folder, then bin/gourmet works.  Just gourmet, which uses /usr/local/bin/gourmet fails.
 
Something is not right with setup.py install.  Mentioned earlier, that I am a programmer.  I do not know the ubuntu / python environment well enough to safely make changes to the installation, given the number of files copied and processed I saw during the install.  Inside the program itself, to adjust logic and field validations, I'm fine.  Though a working test suite would make it safer.

**Comment by jeremyrjk** [comment]
No matter which directory I cd into, I still get this error about util...

**Comment by googlymog** [comment]
I have submitted a PR (#830) that fixes this bug, but the patch is one line so you can do it yourself for faster results.  Search for the setup() function at the bottom of setup.py. From here locate the packages list and add a new entry with 'gourmet.util'.  Let us know if you have any problems.  Thanks.

**Comment by jeremyrjk** [comment]
That worked. But now I'm getting this:

[jeremy@jeremy ~]$ gourmet
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "/usr/bin/gourmet", line 17, in <module>
    GourmetRecipeManager.startGUI()
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 686, in startGUI
    r=RecGui(splash_label=splash.label)
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 896, in __init__
    GourmetApplication.__init__(self, splash_label=splash_label)
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 67, in __init__
    self.setup_prefs() # Setup preferences...
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 89, in setup_prefs
    buttons={'clear_remembered_optional_button':lambda *args: self.forget_remembered_optional_ingredients()}
  File "/usr/lib/python2.7/site-packages/gourmet/prefsGui.py", line 60, in __init__
    self.ui.add_from_file(uifile)
glib.GError: Invalid root element: 'html'

**Comment by googlymog** [comment]
Unfortunately I don't have a quick fix for that.  It looks like it is a completely separate error having to do with GTK / Glade (which I know little about).  I will look into it.  Could you file another issue?

**Comment by jeremyrjk** [comment]
Link to new issue if anyone needs it:
[GTK / Glade error when trying to run Gourmet](https://github.com/thinkle/gourmet/issues/835)
