### ISSUE TITLE
Unable to print from MySql Backend

### ISSUE THREAD

**Issue by magno32** [thinkle/gourmet#804]
I am using MySql as a permanent store for my data.  When I try to print (regardless of what is in the recipe) I get an error:

```
emit ('error', 1, 'Error during Exporter', 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/gourmet/threadManager.py", line 97, in run\n    self.do_run()\n  File "/usr/local/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 394, in _\n    retval = f(self,*args,**kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/gourmet/exporters/exporter.py", line 552, in do_run\n    self.append_referenced_recipes()\n  File "/usr/local/lib/python2.7/dist-packages/gourmet/exporters/exporter.py", line 526, in append_referenced_recipes\n    \'select * from ingredients where recipe_id=? and refid is not null\',r.id\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1614, in execute\n    return connection.execute(statement, *multiparams, **params)\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 662, in execute\n    params)\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 805, in _execute_text\n    statement, parameters\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context\n    context)\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1027, in _handle_dbapi_exception\n    util.reraise(*exc_info)\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context\n    context)\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute\n    cursor.execute(statement, parameters)\n  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 159, in execute\n    query = query % db.literal(args)\nTypeError: not all arguments converted during string formatting\n')
    emit ('done',)
    Syntax Warning: May not be a PDF file (continuing anyway)
    Syntax Error: Couldn't find trailer dictionary
    Syntax Error: Couldn't read xref table
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/gourmet/plugins/import_export/pdf_plugin/print_plugin.py", line 167, in begin_print
        self.set_document(fn, operation,context)
      File "/usr/local/lib/python2.7/dist-packages/gourmet/plugins/import_export/pdf_plugin/print_plugin.py", line 65, in set_document
        self.d = poppler.document_new_from_file(filename,None)
    glib.GError: PDF document is damaged
    There was an error generating a PDF to print.
    Error during Exporter
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/gourmet/threadManager.py", line 97, in run
        self.do_run()
      File "/usr/local/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 394, in _
        retval = f(self,*args,**kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gourmet/exporters/exporter.py", line 552, in do_run
        self.append_referenced_recipes()
      File "/usr/local/lib/python2.7/dist-packages/gourmet/exporters/exporter.py", line 526, in append_referenced_recipes
        'select * from ingredients where recipe_id=? and refid is not null',r.id
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1614, in execute
        return connection.execute(statement, *multiparams, **params)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 662, in execute
        params)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 805, in _execute_text
        statement, parameters
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
        context)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1027, in _handle_dbapi_exception
        util.reraise(*exc_info)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
        context)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute
        cursor.execute(statement, parameters)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 159, in execute
        query = query % db.literal(args)
    TypeError: not all arguments converted during string formatting

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/gourmet/plugins/import_export/pdf_plugin/print_plugin.py", line 174, in handle_error
        raise Exception('There was an error generating a PDF to print')
    Exception: There was an error generating a PDF to print
```

This same issue appears if I try to export to a Gourmet XML file.

I am using 0.17.4, built from source.  I tried with the Ubuntu repo version, then built from source.

**Comment by allenerenee** [comment]
This sounds similar to a problem I had a while ago. However, it mysteriously stopped happening before I was able to capture the error to post here.

**Comment by rabe002** [comment]
I have the same problem with printing or exporting the recipe out of gourmet by using mysql backend. If I do not use the mysql database the printing work.
I tested the character sets with the sql command:  SHOW VARIABLES LIKE 'char%' .
The result was:
+--------------------------+----------------------------+
| Variable_name         | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | utf8                       |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
Is one of the settings false?
The messages from gourmet are attached.
[gourmet.txt](https://github.com/thinkle/gourmet/files/126988/gourmet.txt)

Thank you

**Comment by holocronweaver** [comment]
Still an issue, cannot perform any of the exports because of it (PDF, MCB, HTML, etc).

**Comment by holocronweaver** [comment]
I figured it out. From `exporter.append_referenced_recipes` in `exporters/exporter.py`:

```
reffed = self.rd.db.execute(
    'select * from ingredients where recipe_id=? and refid is not null',r.id
 )
```

`pymysql` does not support the `?` substitution syntax; it directly uses a Python string substitution via `%`. Hence abiding by the rules of the `%` string substitution operator fixes the problem:

```
reffed = self.rd.db.execute(
    'select * from ingredients where recipe_id=%s and refid is not null', (r.id,)
 )
```
