### ISSUE TITLE
problems while exporting recipes as pdf 

### ISSUE THREAD

**Issue by mikey31415** [thinkle/gourmet#850]
I have a database with 215 recipes.  When I attempt to export all recipes as a large PDF document I get an error message "Error: Error during Exporter".  A pop-up window occurs with the Traceback contents given below...  Please help if you can.  Thanks.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gourmet/threadManager.py", line 97, in run
    self.do_run()
  File "/usr/local/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 394, in _
    retval = f(self,*args,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gourmet/exporters/exporter.py", line 571, in do_run
    self.write_footer()
  File "/usr/local/lib/python2.7/dist-packages/gourmet/plugins/import_export/pdf_plugin/pdf_exporter.py", line 681, in write_footer
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/gourmet/plugins/import_export/pdf_plugin/pdf_exporter.py", line 388, in close
    try: self.doc.build(self.txt)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 916, in build
    self._endBuild()
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 858, in _endBuild
    if getattr(self,'_doSave',1): self.canv.save()
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfgen/canvas.py", line 1209, in save
    self._doc.SaveToFile(self._filename, self)
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 217, in SaveToFile
    data = self.GetPDFData(canvas)
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 242, in GetPDFData
    return self.format()
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 421, in format
    IOf = IO.format(self)
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 864, in format
    fcontent = format(self.content, document, toplevel=1)   # yes this is at top level
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 78, in format
    f = element.format(document)
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 1595, in format
    return D.format(document)
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 671, in format
    L = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 78, in format
    f = element.format(document)
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 1771, in format
    if f is None: raise ValueError("format not resolved %s" % self.name)
ValueError: format not resolved MrFood.com

**Comment by Boldie** [comment]
Possible duplicate of #792
