### ISSUE TITLE
Problem with Plugins after System Upgrade

### ISSUE THREAD

**Issue by zombiewoof** [thinkle/gourmet#860]
I have just upgraded Ubuntu 14.04 to 16.04 (fresh install). On reinstalling Gourmet, I activated the Browse Recipes plugin. I had no problem getting the database working, but the Browse tab isn't working properly. On starting the program from the command line, I get the following:

~$ gourmet
No gst player
No windows player
WARNING: Plugin module import failed
PATH: ['/usr/lib/python2.7/dist-packages/', '/usr/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/share/gourmet/plugins', '/usr/lib/python2.7/dist-packages/gourmet/plugins', '/usr/lib/python2.7/dist-packages/gourmet/plugins/import_export']
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 259, in get_module
    self._loaded = __import__(self.module)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/spellcheck/**init**.py", line 1, in <module>
    import reccard_spellcheck_plugin
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/spellcheck/reccard_spellcheck_plugin.py", line 1, in <module>
    import gtk, gtkspell
ImportError: No module named gtkspell
WARNING: Failed to load plugin spellcheck
ERROR:root:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 93, in load_active_plugins
    self.active_plugins.extend(self.available_plugin_sets[p].plugins)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 272, in **getattr**
    if attr == 'plugins': return self.get_plugins()
  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 278, in get_plugins
    return self.get_module().plugins
AttributeError: 'NoneType' object has no attribute 'plugins'

I can open the Browse tab and see the categories, but clicking a category does nothing, in the program window, but generates the following in terminal:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/browse_recipes/browser.py", line 161, in item_activated_cb
    self.switch_model(step,val)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/browse_recipes/browser.py", line 43, in switch_model
    self.build_model(path,val)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/browse_recipes/browser.py", line 52, in build_model
    self.build_recipe_model(path,val)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/browse_recipes/browser.py", line 146, in build_recipe_model
    pb = get_recipe_image(recipe)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/browse_recipes/icon_helpers.py", line 114, in get_recipe_image
    cookPB = make_cooktime_icon(rec.cooktime)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/browse_recipes/icon_helpers.py", line 175, in make_cooktime_icon
    return make_time_icon(cooktime,mode=COOK)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/browse_recipes/icon_helpers.py", line 184, in make_time_icon
    slice_pb = get_time_slice(time)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/browse_recipes/icon_helpers.py", line 151, in get_time_image
    return self.get_image( (time_in_seconds/float(60_60_12) \* 360), 'blue')
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/browse_recipes/icon_helpers.py", line 142, in get_image
    self.slices[(angle,color)] = get_pixbuf_from_image(img)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/browse_recipes/icon_helpers.py", line 41, in get_pixbuf_from_image
    image.tostring(),
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 695, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.

The application was installed using 'sudo apt install gourmet', so the official repository version was installed. The version is 0.17.4.

**Comment by zombiewoof** [comment]
Managed to figure out why the recipes don't display in Browse Mode. Has to do with the fact that depreciated 'tostring' has been removed in python 2.7. Error message that follows, was the clue:

File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 695, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.

This command only appears once, in the script. Replacing it with 'tobytes' fixed the problem.

I'd recommend that this change be made in the source so that future packages will operate correctly.

**Comment by radfordlax** [comment]
I am having a similar problem.  After installing Ubuntu 16.04 I can open the database, but I can not edit or add new recipes.  In order to export I have to turn of the nutritional plugin or it hangs up.  The spell check request also fails in my listing.

**Comment by jdunmire** [comment]
On Ubuntu 16.04, gtkspell has been changed to gtkspellcheck. Changing the import command at the top of reccard_spellcheck_plugin.py solves the problem.

The problem I'm left with is that I can't export. The error I get is:
Return exporter instance
emit ('error', 1, 'Error during Exporter', 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/gourmet/threadManager.py", line 98, in run\n    self.do_run()\n  File "/usr/local/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 395, in _\n    retval = f(self,*args,**kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/gourmet/exporters/exporter.py", line 583, in do_run\n    self.write_footer()\n  File "/usr/local/lib/python2.7/dist-packages/gourmet/plugins/import_export/gxml_plugin/gxml2_exporter.py", line 128, in write_footer\n    encoding = "UTF-8")\n  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1747, in writexml\n    writer.write(\'<?xml version="1.0" encoding="%s"?>%s\' % (encoding, newl))\nAttributeError: \'unicode\' object has no attribute \'write\'\n')
emit ('done',)

**Comment by jdunmire** [comment]
I created a separate issue for the export problem. See #863
