### ISSUE TITLE
Get an IOError when I want to import webpage

### ISSUE THREAD

**Issue by nedkellddv** [thinkle/gourmet#902]
Get the following error when I want to import a webpage

Any advise?

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gourmet/threadManager.py", line 97, in run
    self.do_run()
  File "/usr/lib/python2.7/dist-packages/gourmet/importers/webextras.py", line 18, in do_run
    self.read()
  File "/usr/lib/python2.7/dist-packages/gourmet/importers/webextras.py", line 23, in read
    sock = urllib.urlopen(self.url)
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by FriedrichFroebel** [comment]
According to the error message the SSL handshake failed. Are you able to access the page directly without problems? Which site raises this error?

**Comment by nedkellddv** [comment]
Yes through my browser there is no problem. All sites I want to import.

A google search seemed to me that there has been other problems with python2.7, although my technical understand is not very big, so could not see if there was a solution that related to my problem.

Sorry to be trouble

**Comment by kb5uxg** [comment]
I have this same problem. I cannot import a webpage in either the linux version or windows.
