### ISSUE TITLE
Printing and exporting as PDF does not work

### ISSUE THREAD

**Issue by tastytea** [thinkle/gourmet#906]
Gourmet: 0.17.4
poppler-python: 0.12.1
reportlab: 3.3.0
OS: Gentoo Linux

I'm attaching the [logfile](https://github.com/thinkle/gourmet/files/1990406/gourmet.log), I think this is the relevant part:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gourmet/plugins/import_export/pdf_plugin/print_plugin.py", line 101, in custom_widget_apply
    self.args = self.ppt.get_args_from_opts(self.opts)
  File "/usr/lib64/python2.7/site-packages/gourmet/plugins/import_export/pdf_plugin/pdf_exporter.py", line 917, in get_args_from_opts
    args['pagemode'] = self.page_modes[opts[self.OPT_PO][1]] # PAGE MODE
KeyError: None
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gourmet/plugins/import_export/pdf_plugin/print_plugin.py", line 160, in begin_print
    pe = pdf_exporter.PdfExporterMultiDoc(self.rd,self.recs,fn,pdf_args=self.args,
AttributeError: PDFRecipePrinter instance has no attribute 'args'
```

**Comment by tastytea** [comment]
It works now, although i don't know why.
