### ISSUE TITLE
Installing traceback error 

### ISSUE THREAD

**Issue by MarkP2015** [thinkle/gourmet#926]
mark@Lexington:~/gourmet-0.17.4$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    from DistUtilsExtra.command import build_extra, build_i18n, build_icons
ImportError: No module named DistUtilsExtra.command

Did I do something wrong? I thought I was following the INSTALL.md pretty well.

**Comment by MarkP2015** [comment]
I apologize in advance. I've lost my ability to find what/where/when I have previously posted (asking for help here). Today, a see that I have python-minimal (2.7) installed. So why has this happened?

mark@Lexington:~/gourmet-master$ gourmet
Traceback (most recent call last):
  File "/usr/local/bin/gourmet", line 17, in <module>
    GourmetRecipeManager.startGUI()
  File "/usr/local/lib/python2.7/dist-packages/gourmet/GourmetRecipeManager.py", line 701, in startGUI
    r=RecGui(splash_label=splash.label)
  File "/usr/local/lib/python2.7/dist-packages/gourmet/GourmetRecipeManager.py", line 911, in __init__
    GourmetApplication.__init__(self, splash_label=splash_label)
  File "/usr/local/lib/python2.7/dist-packages/gourmet/GourmetRecipeManager.py", line 76, in __init__
    self.setup_prefs() # Setup preferences...
  File "/usr/local/lib/python2.7/dist-packages/gourmet/GourmetRecipeManager.py", line 99, in setup_prefs
    lambda *args: self.forget_remembered_optional_ingredients()}
  File "/usr/local/lib/python2.7/dist-packages/gourmet/prefsGui.py", line 60, in __init__
    self.ui.add_from_file(uifile)
glib.GError: Failed to open file “/usr/local/share/ui/preferenceDialog.ui”: No such file or directory
