### ISSUE TITLE
ImportError: No module named Image

### ISSUE THREAD

**Issue by MarkP2015** [thinkle/gourmet#927]
I've been struggling with GRM for the last 18 months. I was not able to find the correct tarball instructions and dependencies and even after making some progress, still no working GRM. I've tried netsearching for "ImportError: No module named Image

mark@Lexington:~$ gourmet
Traceback (most recent call last):
  File "/usr/local/bin/gourmet", line 16, in <module>
    from gourmet import GourmetRecipeManager
  File "/usr/local/lib/python2.7/dist-packages/gourmet/__init__.py", line 5, in <module>
    import gglobals
  File "/usr/local/lib/python2.7/dist-packages/gourmet/gglobals.py", line 138, in <module>
    from gtk_extras import dialog_extras
  File "/usr/local/lib/python2.7/dist-packages/gourmet/gtk_extras/dialog_extras.py", line 2, in <module>
    import gtk, gobject, os.path, optionTable, thumbnail, fnmatch,  re
  File "/usr/local/lib/python2.7/dist-packages/gourmet/gtk_extras/thumbnail.py", line 6, in <module>
    import Image
ImportError: No module named Image

**Comment by FriedrichFroebel** [comment]
It seems like the `Pillow` package is missing for your installation of Python 2.7 - installing it via PIP should work.

**Comment by FriedrichFroebel** [comment]
`sudo aptitude install python-pillow` should work. An alternative would be to use something like `sudo python -m pip install pillow` which uses PIP instead of your system's package manager.

**Comment by MarkP2015** [comment]
mark@Lexington:~$ sudo aptitude install python-pillow
[sudo] password for mark: 
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
                                         
mark@Lexington:~$ sudo python -m pip install pillow
The directory '/home/mark/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/mark/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pillow in /usr/lib/python2.7/dist-packages (5.1.0)
mark@Lexington:~$ sudo aptitude install gourmet
gourmet is already installed at the requested version (0.17.4-6)
gourmet is already installed at the requested version (0.17.4-6)
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
                                         
mark@Lexington:~$ gourmet
Traceback (most recent call last):
  File "/usr/local/bin/gourmet", line 17, in <module>
    GourmetRecipeManager.startGUI()
  File "/usr/local/lib/python2.7/dist-packages/gourmet/GourmetRecipeManager.py", line 701, in startGUI
    r=RecGui(splash_label=splash.label)
  File "/usr/local/lib/python2.7/dist-packages/gourmet/GourmetRecipeManager.py", line 911, in __init__
    GourmetApplication.__init__(self, splash_label=splash_label)
  File "/usr/local/lib/python2.7/dist-packages/gourmet/GourmetRecipeManager.py", line 76, in __init__
    self.setup_prefs() # Setup preferences...
  File "/usr/local/lib/python2.7/dist-packages/gourmet/GourmetRecipeManager.py", line 99, in setup_prefs
    lambda *args: self.forget_remembered_optional_ingredients()}
  File "/usr/local/lib/python2.7/dist-packages/gourmet/prefsGui.py", line 60, in __init__
    self.ui.add_from_file(uifile)
glib.GError: Failed to open file “/usr/local/share/ui/preferenceDialog.ui”: No such file or directory
