### ISSUE TITLE
Error in exporting

### ISSUE THREAD

**Issue by MarkP2015** [thinkle/gourmet#950]
Please pardon my ignorance. I don't know whether this is a GRM problem, or my problem. I did a fresh install of my OS today (Ubuntu 18.04) and used the Ubuntu Software Installer to install GRM. It didn't report any errors during the install. I manually added with "import a file" about 20 recipes with the .grmt extension. No problems reported. When I tried to export all my recipes (about 1450), I saw this:

In the popup window: "Error 1" and in Details:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gourmet/threadManager.py", line 97, in run
    self.do_run()
  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 394, in _
    retval = f(self,*args,**kwargs)
  File "/usr/lib/python2.7/dist-packages/gourmet/exporters/exporter.py", line 565, in do_run
    e.do_run()
  File "/usr/lib/python2.7/dist-packages/gourmet/exporters/exporter.py", line 79, in do_run
    self._write_text_()
  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 395, in _
    retval = self.run_post_hook(f.__name__,retval,*args,**kwargs)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 355, in run_post_hook
    retval = hook(retval,self,*args,**kwargs)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugin.py", line 185, in do_write
    val = field_fetcher(klass.r)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/nutritional_information/export_plugin.py", line 24, in get_nutritional_info_as_text_blob
    nutinfo = nd.get_nutinfo_for_inglist(rd.get_ings(rec),rd)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/nutritional_information/nutrition.py", line 122, in get_nutinfo_for_inglist
    return NutritionInfoList([self.get_nutinfo_for_ing(i,rd, multiplier) for i in inglist],
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/nutritional_information/nutrition.py", line 116, in get_nutinfo_for_ing
    return  self.get_nutinfo_for_item(ing.ingkey,amount,ing.unit,ingObject=ing)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/nutritional_information/nutrition.py", line 128, in get_nutinfo_for_item
    ni=self.get_nutinfo(key)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/nutritional_information/nutrition.py", line 164, in get_nutinfo
    ni = self.get_nutinfo_from_desc(key)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/nutritional_information/nutrition.py", line 146, in get_nutinfo_from_desc
    matches = self.get_matches(desc)
  File "/usr/lib/python2.7/dist-packages/gourmet/plugins/nutritional_information/nutrition.py", line 81, in get_matches
    words=re.split("\W",key)
  File "/usr/lib/python2.7/re.py", line 171, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or buffer

**Comment by andrearicci** [comment]
similar problem in win10, trying to export all to html:
Traceback (most recent call last):
  File "C:\Users\Bernie\Documents\GitHub\gourmet\gourmet\threadManager.py", line 97, in run
  File "C:\Users\Bernie\Documents\GitHub\gourmet\gourmet\plugin_loader.py", line 394, in _
  File "C:\Users\Bernie\Documents\GitHub\gourmet\gourmet\exporters\exporter.py", line 560, in do_run
IOError: [Errno 2] No such file or directory: u'D:\\ANDREA\\Documents\\Dropbox\\piccino2piccione\\_FOOD\\\xb0\xb0 RICETTE \xb0\xb0\\_GourmetHtmlBackup\\ricette.html\\139cal Onebowl chocolate cake92.html'
