### ISSUE TITLE
Problem on install - Is this project still updated?

### ISSUE THREAD

**Issue by Gahamelas** [thinkle/gourmet#966]
Hi everyone, 
I am getting this error when trying to execute gourmet:

```
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/gourmet ; exit;
(base) --- ~ » /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/gourmet ; exit;
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gourmet/gtk_extras/LinkedTextView.py:80: GtkWarning: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
  hand_cursor = gtk.gdk.Cursor(gtk.gdk.HAND2)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/gourmet", line 16, in <module>
    from gourmet import GourmetRecipeManager
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 7, in <module>
    import prefs, prefsGui, shopgui, reccard
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gourmet/shopgui.py", line 3, in <module>
    import recipeManager, convert, reccard, prefs
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gourmet/reccard.py", line 32, in <module>
    import timeScanner
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gourmet/timeScanner.py", line 5, in <module>
    from gtk_extras import LinkedTextView
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gourmet/gtk_extras/LinkedTextView.py", line 76, in <module>
    class LinkedTextView (gtk.TextView):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gourmet/gtk_extras/LinkedTextView.py", line 80, in LinkedTextView
    hand_cursor = gtk.gdk.Cursor(gtk.gdk.HAND2)
RuntimeError: could not create GdkCursor object
```

Any help, much appreciated.
GM

**Comment by saxon-s** [comment]
Please provide the following information:
- Which Linux distribution and version are you running?
- What is the Gourmet version?
- How was Gourmet installed?

**Comment by Gahamelas** [comment]
1. I am on MacOS Catalina (19E287), MacBook Pro (13-inch, 2016).
2.&3. The last Gourmet version installed via `sudo port install gourmet`

**Comment by Gahamelas** [comment]
Any help would be welcome.

**Comment by saxon-s** [comment]
I unfortunately don't have a Mac to reproduce and investigate this issue. I suspect that something may be missing from your environment. Check that all the required packages are installed. The required packages are listed at the bottom of the Install wiki page: https://github.com/thinkle/gourmet/blob/master/INSTALL.md
