### ISSUE TITLE
Locale error

### ISSUE THREAD

**Issue by allenerenee** [thinkle/gourmet#994]
I've been running Gourmet on Linux Mint 18.3 for more than a year now. After the update that dropped yesterday, though, I'm suddenly getting the following error when I try to start the program:
`(process:9260): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/usr/bin/gourmet", line 16, in <module>
    from gourmet import GourmetRecipeManager
  File "/usr/lib/python2.7/dist-packages/gourmet/__init__.py", line 5, in <module>
    import gglobals
  File "/usr/lib/python2.7/dist-packages/gourmet/gglobals.py", line 3, in <module>
    from gdebug import debug
  File "/usr/lib/python2.7/dist-packages/gourmet/gdebug.py", line 1, in <module>
    from OptionParser import args
  File "/usr/lib/python2.7/dist-packages/gourmet/OptionParser.py", line 2, in <module>
    import version
  File "/usr/lib/python2.7/dist-packages/gourmet/version.py", line 7, in <module>
    elib.intl.install('gourmet', settings.locale_base)
  File "/usr/lib/python2.7/dist-packages/elib/intl/__init__.py", line 472, in install
    _install(domain, localedir, True)
  File "/usr/lib/python2.7/dist-packages/elib/intl/__init__.py", line 416, in _install
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting`

Running `export LC_ALL=C` in the terminal first fixes it for that instance, but does not persist after closing the program.

**Comment by cydanil** [comment]
I gather that the update you're talking about is regarding Linux mint 20?

**Comment by allenerenee** [comment]
Not at all. I am still running 18.3, which is supported through I believe
next year.  This was an ordinary software/ security update.

**Comment by cydanil** [comment]
Thanks, I cannot tell what's happening at the level of Linux Mint and your environment (ie. which locale is set), and I could not reproduce it out of the box. 
However, with the error message that you provided, we'll be able to handle the error smoothly in the next version of Gourmet.

For the time being, I can only suggest that you set a locale prior launching the application, as you've been doing so far.

Thanks!

**Comment by cydanil** [comment]
This issue is now resolved since we've updated internationalization handling in #1013
